version: 0.2
env:
  secrets-manager:
    DOCKER_USERNAME: third_party_tokens:docker_hub_username
    DOCKER_TOKEN: third_party_tokens:docker_hub_token
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo docker version
      - docker -v
      - LATEST_VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/^v//')
      - curl -L "https://github.com/aquasecurity/trivy/releases/download/v${LATEST_VERSION}/trivy_${LATEST_VERSION}_Linux-64bit.rpm" -o trivy.rpm
      - sudo yum install trivy.rpm -y
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ${AWS_REGION} --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to DockerHub
      - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - trivy image --exit-code 1 --severity HIGH,CRITICAL $REPOSITORY_URI:latest --no-progress 
      - if ! trivy --no-progress --exit-code 1 --severity HIGH,CRITICAL $REPOSITORY_URI:latest; then exit 1; fi
      - docker tag $(docker images --filter=reference=$REPOSITORY_URI:latest --format "{{.ID}}") $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo $REPOSITORY_URI
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definition files....
      - printf '[{"name":"'${CONTAINER_NAME}'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinition.json
artifacts:
    files:
      - imagedefinition.json
