version: 0.2

env:
  secrets-manager:
    DOCKER_USERNAME: third_party_tokens:docker_hub_username
    DOCKER_TOKEN: third_party_tokens:docker_hub_token
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo docker version
      - docker -v
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ${AWS_REGION} --no-include-email) 
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to DockerHub...
      - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo $REPOSITORY_URI
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"'${CONTAINER_NAME}'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
